spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://freddyartea3:Fralart0190@user-data.uh2pfh3.mongodb.net/?retryWrites=true&w=majority&appName=user-data
      database: userdb
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: postgres
#    password: sasa
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect



#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8082