global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'configserver'
    static_configs:
      - targets: ['host.docker.internal:8888']
    metrics_path: /actuator/prometheus

  - job_name: 'eureka'
    static_configs:
      - targets: ['host.docker.internal:8761']
    metrics_path: /actuator/prometheus

  - job_name: 'gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /actuator/prometheus

  - job_name: 'product-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: /actuator/prometheus

  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: /actuator/prometheus

  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: /actuator/prometheus

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
    metrics_path: /actuator/prometheus