spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: sasa
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    enabled: false

logging:
  level:
    root: WARN
