spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/arkam_user
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: eureka
    instance-id: ${spring.application.name}:${server.port}


logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rolling policy:
      max-file-size: 5MB
      max-history: 7

# KEYCLOAK
keycloak:
  admin:
    username: user
    password: user
    server-url: http://keycloak:8080
    realm: arkam-app
    client-id: admin-cli
    client-uid: 74d31cf4-5808-43de-93e0-01a079063245