apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'gateway-service'
        static_configs:
          - targets: ['gateway-service:8080']

      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:8082']

      - job_name: 'product-service'
        static_configs:
          - targets: ['product-service:8081']

      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:8083']

      - job_name: 'eureka'
        static_configs:
          - targets: ['eureka:8761']

      - job_name: 'config-server'
        static_configs:
          - targets: ['config-server:8888']