spring:
  application:
    name: configserver
  profiles:
    active: native
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\Freddy\OneDrive\Desktop\ARKAM SpringBoot\arkam-microservices\configserver\src\main\resources\config

server:
  port: 8888

management:
   endpoints:
     web:
       exposure:
         include: "*"
   tracing:
     sampling:
       probability: 1.0
   zipkin:
     tracing:
       endpoint: http://localhost:9411/api/v2/spans