name: Deploy Config Server to AWS with Jib

on:
  push:
    branches:
      - main
    paths:
      - 'configserver/**' # Se activa solo con cambios en la carpeta configserver
      - '.github/workflows/deploy-config-server.yml'
      - 'ecs/config-server-task-definition.json'
  workflow_dispatch: # Permite ejecutarlo manualmente

env:
  AWS_REGION: us-east-1 # Cambia esto a tu región de AWS
  ECS_CLUSTER_NAME: arkam-cluster
  ECS_SERVICE_NAME: config-server-svc
  ECS_TASK_DEFINITION_PATH: ecs/config-server-task-definition.json # Ruta a la nueva plantilla
  CONTAINER_NAME: config-server-container
  IMAGE_REPO: config-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image with Jib
      id: jib
      run: |
        IMAGE_TAG=${{ github.sha }}
        # Apuntamos al pom.xml del configserver
        mvn -f configserver/pom.xml compile jib:build -Dimage=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPO }}:$IMAGE_TAG
        
        echo "image=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPO }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Create new Task Definition with updated image
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION_PATH }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.jib.outputs.image }}

    - name: Deploy new Task Definition to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_NAME }}
        cluster: ${{ env.ECS_CLUSTER_NAME }}
        wait-for-service-stability: true
